micronaut:
  application:
    name: micronautR2dbcTimestampIssue
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://localhost:3306/db
      username: root
      password: ''
